SELECT * FROM customer_behaviour.customer;
-- Q1. What is the total revenue generated by male vs. female customers?
	select  gender , SUM(purchase_amount) AS 'REVENUE' FROM  customer group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
	select customer.customer_id ,customer.purchase_amount from customer where discount_applied='Yes' and purchase_amount >=  (Select avg(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?
	select *from customer order by review_rating desc  limit 5;
    
-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
	 select  shipping_type ,AVG(PURCHASE_AMOUNT) AS AVGERAGE from customer where shipping_type = 'Express' or shipping_type = 'Standard' group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
        select subscription_status , count(customer_id) as total_customer,
        avg(purchase_amount) as AvG_Amount,
        sum(purchase_amount) as Total_Revenue
        from customer
        group by subscription_status
        order by AvG_Amount,Total_Revenue;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
     SELECT 
    CASE 
        WHEN previous_purchases <= 2 THEN 'New'
        WHEN previous_purchases BETWEEN 3 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer
GROUP BY customer_segment
ORDER BY customer_count DESC;

-- Q8. What are the top 3 most purchased products within each category?
		 WITH ranked_products AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchased,
        DENSE_RANK() OVER(PARTITION BY category ORDER BY COUNT(*) DESC) AS product_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    category,
    item_purchased,
    total_purchased,
    product_rank
FROM ranked_products
WHERE product_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
		SELECT 
    COUNT(*) AS total_repeat_buyers,
    SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) AS subscribed_count,
    ROUND(
        (SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) / COUNT(*)) * 100, 
        2
    ) AS subscription_percentage
FROM customer
WHERE previous_purchases > 5;

-- Q10. What is the revenue contribution of each age group?
SELECT 
    group_age,
    SUM(purchase_amount) AS total_revenue,
    ROUND(
        (SUM(purchase_amount) / (SELECT SUM(purchase_amount) FROM customer)) * 100, 
        2
    ) AS revenue_contribution_percentage
FROM customer
GROUP BY group_age
ORDER BY total_revenue DESC;l

